using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UniCore.Api.Helpers;
using UniCore.Api.Modules.PlanEstudios.Managers;
using UniCore.Api.Modules.PlanEstudios.Requests;
using UniCore.Api.Modules.Seguridad.Managers;

namespace UniCore.Api.Modules.PlanEstudios.Controllers;

[ApiController, Route("{conexion}/PlanEstudios"), Authorize]
public sealed class CatalogosRelacionadosController(CatalogosRelacionadosManager manager, AuditoriaManager audit) : ControllerBase
{
    [HttpGet("Idiomas"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.CONSULTAR")]
    public async Task<ActionResult> Idiomas(string conexion, [FromQuery] bool incluirInactivos = false) => Respuesta.Success(await manager.Idiomas(conexion, incluirInactivos));
    [HttpPost("Idiomas"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> CrearIdioma(string conexion, [FromBody] IdiomaRequest r) { r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("idiomas", r.codigo, null, null, conexion) is not null) return Respuesta.Conflict("El código del idioma ya existe."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El estado no existe o está inactivo."); var id = await manager.CrearIdioma(conexion, r); await audit.Registrar(conexion, "aca_idiomas", id.ToString(), "CREAR", nuevo: r); var items = await manager.Idiomas(conexion, true); return Respuesta.Success(items.FirstOrDefault(x => x.cod == id), "Idioma creado."); }
    [HttpPut("Idiomas/{cod:int:min(1)}"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> ActualizarIdioma(string conexion, int cod, [FromBody] IdiomaRequest r) { if (!await manager.Existe("idiomas", cod, conexion)) return Respuesta.NotFound("El idioma no existe."); r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("idiomas", r.codigo, null, cod, conexion) is not null) return Respuesta.Conflict("El código del idioma ya existe."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El estado no existe o está inactivo."); await manager.ActualizarIdioma(conexion, cod, r); await audit.Registrar(conexion, "aca_idiomas", cod.ToString(), "EDITAR", nuevo: r); return Respuesta.Success(await manager.Idiomas(conexion, true), "Idioma actualizado."); }

    [HttpGet("NivelesIdioma"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.CONSULTAR")]
    public async Task<ActionResult> Niveles(string conexion, [FromQuery] bool incluirInactivos = false) => Respuesta.Success(await manager.Niveles(conexion, incluirInactivos));
    [HttpPost("NivelesIdioma"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> CrearNivel(string conexion, [FromBody] NivelIdiomaRequest r) { r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("niveles", r.codigo, null, null, conexion) is not null) return Respuesta.Conflict("El código del nivel ya existe."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El estado no existe o está inactivo."); var id = await manager.CrearNivel(conexion, r); await audit.Registrar(conexion, "aca_niveles_idioma", id.ToString(), "CREAR", nuevo: r); return Respuesta.Success(id, "Nivel de idioma creado."); }
    [HttpPut("NivelesIdioma/{cod:int:min(1)}"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> ActualizarNivel(string conexion, int cod, [FromBody] NivelIdiomaRequest r) { if (!await manager.Existe("niveles", cod, conexion)) return Respuesta.NotFound("El nivel no existe."); r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("niveles", r.codigo, null, cod, conexion) is not null) return Respuesta.Conflict("El código del nivel ya existe."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El estado no existe o está inactivo."); await manager.ActualizarNivel(conexion, cod, r); await audit.Registrar(conexion, "aca_niveles_idioma", cod.ToString(), "EDITAR", nuevo: r); return Respuesta.Success(await manager.Niveles(conexion, true), "Nivel de idioma actualizado."); }

    [HttpGet("RutasIdioma"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.CONSULTAR")]
    public async Task<ActionResult> Rutas(string conexion, [FromQuery] int? cod_idioma = null, [FromQuery] bool incluirInactivos = false) => Respuesta.Success(await manager.Rutas(conexion, cod_idioma, incluirInactivos));
    [HttpPost("RutasIdioma"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> CrearRuta(string conexion, [FromBody] RutaIdiomaRequest r) { r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("rutas", r.codigo, r.cod_idioma, null, conexion) is not null) return Respuesta.Conflict("El código ya existe para este idioma."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El idioma, nivel final o estado no es válido."); var id = await manager.CrearRuta(conexion, r); await audit.Registrar(conexion, "aca_rutas_idioma", id.ToString(), "CREAR", nuevo: r); return Respuesta.Success(await manager.Rutas(conexion, r.cod_idioma, true), "Ruta creada."); }
    [HttpPut("RutasIdioma/{cod:int:min(1)}"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> ActualizarRuta(string conexion, int cod, [FromBody] RutaIdiomaRequest r) { if (!await manager.Existe("rutas", cod, conexion)) return Respuesta.NotFound("La ruta no existe."); r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("rutas", r.codigo, r.cod_idioma, cod, conexion) is not null) return Respuesta.Conflict("El código ya existe para este idioma."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El idioma, nivel final o estado no es válido."); await manager.ActualizarRuta(conexion, cod, r); await audit.Registrar(conexion, "aca_rutas_idioma", cod.ToString(), "EDITAR", nuevo: r); return Respuesta.Success(await manager.Rutas(conexion, r.cod_idioma, true), "Ruta actualizada."); }
    [HttpPut("RutasIdioma/{cod:int:min(1)}/Asignaturas"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> AsignaturasRuta(string conexion, int cod, [FromBody] RutaAsignaturasRequest r) { try { await manager.ReemplazarAsignaturasRuta(conexion, cod, r.asignaturas); } catch (InvalidOperationException ex) { return Respuesta.Failed<object>(mensaje: ex.Message); } await audit.Registrar(conexion, "aca_ruta_idioma_asignaturas", cod.ToString(), "REEMPLAZAR", nuevo: r); return Respuesta.Success(await manager.Rutas(conexion, null, true), "Asignaturas de ruta actualizadas."); }

    [HttpGet("CertificacionesIdioma"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.CONSULTAR")]
    public async Task<ActionResult> Certificaciones(string conexion, [FromQuery] int? cod_idioma = null, [FromQuery] bool incluirInactivos = false) => Respuesta.Success(await manager.Certificaciones(conexion, cod_idioma, incluirInactivos));
    [HttpPost("CertificacionesIdioma"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> CrearCertificacion(string conexion, [FromBody] CertificacionIdiomaRequest r) { r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("certificaciones", r.codigo, r.cod_idioma, null, conexion) is not null) return Respuesta.Conflict("El código ya existe para este idioma."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El idioma o estado no es válido."); var id = await manager.CrearCertificacion(conexion, r); await audit.Registrar(conexion, "aca_certificaciones_idioma", id.ToString(), "CREAR", nuevo: r); return Respuesta.Success(await manager.Certificaciones(conexion, r.cod_idioma, true), "Certificación creada."); }
    [HttpPut("CertificacionesIdioma/{cod:int:min(1)}"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> ActualizarCertificacion(string conexion, int cod, [FromBody] CertificacionIdiomaRequest r) { if (!await manager.Existe("certificaciones", cod, conexion)) return Respuesta.NotFound("La certificación no existe."); r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("certificaciones", r.codigo, r.cod_idioma, cod, conexion) is not null) return Respuesta.Conflict("El código ya existe para este idioma."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El idioma o estado no es válido."); await manager.ActualizarCertificacion(conexion, cod, r); await audit.Registrar(conexion, "aca_certificaciones_idioma", cod.ToString(), "EDITAR", nuevo: r); return Respuesta.Success(await manager.Certificaciones(conexion, r.cod_idioma, true), "Certificación actualizada."); }
    [HttpPut("CertificacionesIdioma/{cod:int:min(1)}/Niveles"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> NivelesCertificacion(string conexion, int cod, [FromBody] CertificacionNivelesRequest r) { try { await manager.ReemplazarNivelesCertificacion(conexion, cod, r.niveles); } catch (InvalidOperationException ex) { return Respuesta.Failed<object>(mensaje: ex.Message); } await audit.Registrar(conexion, "aca_certificacion_idioma_niveles", cod.ToString(), "REEMPLAZAR", nuevo: r); return Respuesta.Success(await manager.Certificaciones(conexion, null, true), "Niveles acreditables actualizados."); }

    [HttpGet("ActividadesCocurriculares"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.CONSULTAR")]
    public async Task<ActionResult> Actividades(string conexion, [FromQuery] bool incluirInactivos = false) => Respuesta.Success(await manager.Actividades(conexion, incluirInactivos));
    [HttpPost("ActividadesCocurriculares"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> CrearActividad(string conexion, [FromBody] ActividadCocurricularRequest r) { r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("actividades", r.codigo, null, null, conexion) is not null) return Respuesta.Conflict("El código de actividad ya existe."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El tipo de actividad o estado no es válido."); var id = await manager.CrearActividad(conexion, r); await audit.Registrar(conexion, "aca_actividades_cocurriculares", id.ToString(), "CREAR", nuevo: r); return Respuesta.Success(await manager.Actividades(conexion, true), "Actividad creada."); }
    [HttpPut("ActividadesCocurriculares/{cod:int:min(1)}"), Authorize(Policy = "PERMISO:PLAN_ESTUDIOS.ADMINISTRAR")]
    public async Task<ActionResult> ActualizarActividad(string conexion, int cod, [FromBody] ActividadCocurricularRequest r) { if (!await manager.Existe("actividades", cod, conexion)) return Respuesta.NotFound("La actividad no existe."); r.codigo = r.codigo.Trim().ToUpperInvariant(); if (await manager.ExisteCodigo("actividades", r.codigo, null, cod, conexion) is not null) return Respuesta.Conflict("El código de actividad ya existe."); if (!await manager.ReferenciasValidas(r, conexion)) return Respuesta.Failed<object>(mensaje: "El tipo de actividad o estado no es válido."); await manager.ActualizarActividad(conexion, cod, r); await audit.Registrar(conexion, "aca_actividades_cocurriculares", cod.ToString(), "EDITAR", nuevo: r); return Respuesta.Success(await manager.Actividades(conexion, true), "Actividad actualizada."); }
}
